---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-01.mybluemix.net/eureka/,https://eureka-server-02.mybluemix.net/eureka/https://eureka-server-03.mybluemix.net/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: subject
words: It,U,Had
  
---
spring:
  profiles: verb
words: radsjn,knewsdsja,hadfdskjf,sajfsaw,boufsajkght

---
spring:
  profiles: article
words: aasfj,thejfsafs

---
spring:
  profiles: adjective
words: reasonableasfjk,leakyasfj,suspiciousasfkj,ordinaryasf
---
spring:
  profiles: noun
words: boataskj,bookfsakj,voteadsk,seatasdk,backpackdsalk,partitionlksda,groundhogsaksa
  
