---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://commmon-eureka-server.mybluemix.net/eureka/
      #,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  profiles: subject
words: It,U,Had
  
---
spring:
  profiles: verb
words: radsjn,knewsdsja,hadfdskjf,sajfsaw,boufsajkght

---
spring:
  profiles: article
words: aasfj,thejfsafs

---
spring:
  profiles: adjective
words: reasonableasfjk,leakyasfj,suspiciousasfkj,ordinaryasf
---
spring:
  profiles: noun
words: boataskj,bookfsakj,voteadsk,seatasdk,backpackdsalk,partitionlksda,groundhogsaksa
  
